# Generated by Django 3.0.2 on 2020-02-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DCSCodexAdmin', '0005_auto_20200223_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='group',
        ),
    ]
