# Generated by Django 3.0.2 on 2020-02-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DCSCodexAdmin', '0006_remove_notification_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='users', to='DCSCodexAdmin.Group'),
        ),
    ]
