# Generated by Django 3.0.2 on 2020-02-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DCSCodexAdmin', '0008_auto_20200223_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DCSCodexAdmin.Group'),
        ),
    ]
